// <auto-generated />
namespace Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_HouseType_table_with_unique_type : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_HouseType_table_with_unique_type));
        
        string IMigrationMetadata.Id
        {
            get { return "201708062025435_added_HouseType_table_with_unique_type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
