// <auto-generated />
namespace Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_delete_on_cascade_for_AttractionReservation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_delete_on_cascade_for_AttractionReservation));
        
        string IMigrationMetadata.Id
        {
            get { return "201709111440030_added_delete_on_cascade_for_AttractionReservation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
