// <auto-generated />
namespace Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_delete_on_cascade_for_Attraction_Reservation_Worker : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_delete_on_cascade_for_Attraction_Reservation_Worker));
        
        string IMigrationMetadata.Id
        {
            get { return "201709160536026_Added_delete_on_cascade_for_Attraction_Reservation_Worker"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
