// <auto-generated />
namespace Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class extended_length_name_description_in_Attraction_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(extended_length_name_description_in_Attraction_table));
        
        string IMigrationMetadata.Id
        {
            get { return "201708072226082_extended_length_name_description_in_Attraction_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
